version: '2'
services:
 
  sqlserver:
    image: microsoft/mssql-server-windows-developer
    container_name: popquiz_sql
    ports:
      ["1433:1433"]
    volumes:
      - c:\temp:c:\temp
    environment:
      sa_password: P@ssW0rd
      accept_eula: Y
      attach_dbs: "[{'dbName':'popquiz','dbFiles':['c:\\\\temp\\\\popquiz.mdf','c:\\\\temp\\\\popquiz_log.ldf']}]"
    networks:
      default:
        ipv4_address: 192.168.128.99
        aliases:
          - pq_sql
  
networks:
  default:
    external:
      name: nat